name: gvault
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_secure_storage: ^5.0.2
  pointycastle: ^3.5.2
  crypto: ^3.0.1
  convert: ^3.0.1
  path_provider: ^2.0.9
  sqflite: ^2.0.2
  image_picker: ^0.8.5
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.13
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

